//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_USER
    {
        public decimal ID { get; set; }
        public string UserAccount { get; set; }
        public string UserPWD { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<decimal> UpdateID { get; set; }
        public Nullable<decimal> Emp_ID { get; set; }
    
        public virtual BASE_EMPLOYEE BASE_EMPLOYEE { get; set; }
    }
}
