//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_ROLE
    {
        public decimal ROLE_ID { get; set; }
        public Nullable<decimal> DATA_AUTH_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public string ALLOW_DEL { get; set; }
        public string DEFAULT_ROLE { get; set; }
        public string REMARK { get; set; }
        public string STATE { get; set; }
        public Nullable<decimal> SORT { get; set; }
    }
}
