//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_CITY
    {
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string CODE { get; set; }
        public string ORG_LEVEL { get; set; }
        public string PARENTCODE { get; set; }
        public Nullable<decimal> PARENTID { get; set; }
        public string CONTRY { get; set; }
        public string LOC_X { get; set; }
        public string LOC_Y { get; set; }
        public string STATE { get; set; }
    }
}
