//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLib.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManagerSiContext : DbContext
    {
        public ManagerSiContext()
            : base("name=ManagerSiContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BASE_CITY> BASE_CITY { get; set; }
        public virtual DbSet<房屋租赁表> 房屋租赁表 { get; set; }
        public virtual DbSet<House_Lease> House_Lease { get; set; }
        public virtual DbSet<BASE_EMPLOYEE> BASE_EMPLOYEE { get; set; }
        public virtual DbSet<BASE_ROLE> BASE_ROLE { get; set; }
        public virtual DbSet<BASE_USER> BASE_USER { get; set; }
    }
}
