//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class House_Lease
    {
        public decimal ID { get; set; }
        public string Districts { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string Community { get; set; }
        public Nullable<int> Room_Num { get; set; }
        public Nullable<int> Parlor_Num { get; set; }
        public Nullable<int> Kitchen_Num { get; set; }
        public Nullable<int> Bathroom_Num { get; set; }
        public Nullable<double> Area { get; set; }
        public string Orientation { get; set; }
        public Nullable<int> Room_Floor { get; set; }
        public Nullable<int> Total_Floor { get; set; }
        public string Renovation { get; set; }
        public Nullable<int> Year_Built { get; set; }
        public string House_Type { get; set; }
        public Nullable<double> Price { get; set; }
        public string Lease_Type { get; set; }
        public string Contacts { get; set; }
        public string Mobile { get; set; }
        public string Update_By { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
        public string Biz_date { get; set; }
        public string State { get; set; }
    }
}
