//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class 房屋租赁表
    {
        public decimal ID { get; set; }
        public Nullable<System.DateTime> 登记时间 { get; set; }
        public string 市区 { get; set; }
        public string 街道1 { get; set; }
        public string 街道2 { get; set; }
        public string 小区 { get; set; }
        public Nullable<int> 室 { get; set; }
        public Nullable<int> 厅 { get; set; }
        public Nullable<int> 厨 { get; set; }
        public Nullable<int> 卫 { get; set; }
        public Nullable<double> 面积 { get; set; }
        public string 朝向 { get; set; }
        public Nullable<int> 所在楼层 { get; set; }
        public Nullable<int> 总楼层 { get; set; }
        public string 装修 { get; set; }
        public Nullable<int> 建筑年代 { get; set; }
        public string 房屋类型 { get; set; }
        public Nullable<double> 费用 { get; set; }
        public string 委托类型 { get; set; }
        public string 联系电话 { get; set; }
        public string 联系人 { get; set; }
        public string 登记人 { get; set; }
        public Nullable<System.DateTime> 更新时间 { get; set; }
        public string State { get; set; }
    }
}
