


//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;
using DataBaseLib.Model;

namespace DataBaseLib.DAL
{
    public partial class UnitOfWork : DataBaseLib.Infrastructure.DAL.UnitOfWork
    {
       public DataBaseLib.Model.ManagerSiContext Context { get { return context as DataBaseLib.Model.ManagerSiContext; } }
       public UnitOfWork(DataBaseLib.Model.ManagerSiContext context) : base(context)
       {
       }
       
       
       public UnitOfWork() : this(DataBaseLib.Model.ManagerSiContext.CurrentHttpContext){
        
       }
       
       public int? ContextCommandTimeOut {
         get {
            return Context.GetCommandTimeout();
          }
          set {
            Context.SetCommandTimeout(value);
          }
        }
    	
    /// <summary>
    /// 注册
    /// </summary>
      private BASE_CITY_dal _BaseCityRepository = null;
      public BASE_CITY_dal BaseCityRepository {
        get
    	{
    	  if (_BaseCityRepository == null)
    	  {
              _BaseCityRepository = new BASE_CITY_dal(this);
    	  }
    	  return _BaseCityRepository;
    	}
      }

        /// <summary>
        /// 注册
        /// </summary>
        private 房屋租赁表_dal _房屋租赁表Repository = null;
        public 房屋租赁表_dal 房屋租赁表Repository {
            get {
                if (_房屋租赁表Repository == null) {
                    _房屋租赁表Repository = new 房屋租赁表_dal(this);
                }
                return _房屋租赁表Repository;
            }
        }


    }
}

